title: Apicurio
description: 'Open Source API Design and Registry.'
url: 'https://www.apicur.io'
_baseurl: 'https://www.apicur.io'
github_username: apicurio
github_url: https://github.com/apicurio
github_studio_url: https://github.com/apicurio/apicurio-studio
github_registry_url: https://github.com/apicurio/apicurio-registry
github_apicurito_url: https://github.com/apicurio/apicurito
github_datamodels_url: https://github.com/apicurio/apicurio-data-models
docker_hub_url: https://hub.docker.com/r/apicurio
try_now_url: https://studio.apicur.io/
mas_registry_url: https://console.redhat.com/beta/application-services/service-registry?quickstart=quarkus-kafka
mas_cli_url: https://github.com/redhat-developer/app-services-cli/releases
email: apiman-user@lists.jboss.org
future: true
quickstart: true
excerpt_separator: '---'
plugins:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jemoji
sass:
    style: compressed
collections:
    docs: {output: true, permalink: '/docs/:path/'}
defaults:
    - {scope: {type: docs}, values: {layout: docs}}
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:year/:month/:day/:title'}}
    - {scope: {path: ""}, values: {image: {path: /images/opengraph.png, width: 1200, height: 630}}}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
include:
    - _pages
twitter_username: Apicurio
twitter:
    username: Apicurio
